services:
  db:
    container_name: db_online_ticket_office
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db_data_online_ticket_office:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend_online_ticket_office

networks:
  backend_online_ticket_office:
    driver: bridge
    name: backend_online_ticket_office

volumes:
  db_data_online_ticket_office:
